-- DMM migration 1.6.0 -> 1.6.1
-- Flip community YAML discovery on, ONCE. Dolibarr's _load_tables() replays every
-- update_*.sql on each module activation/upgrade, so an unconditional UPDATE would
-- re-enable the setting on every activation and silently override a user who turned
-- it off.
--
-- The original one-shot flip is intentionally retired here: gating it portably (MySQL
-- forbids referencing the UPDATE target table in a subquery) is fragile, and the new
-- installs already default community_yaml_enabled to '0' in data.sql. The setting is
-- now left under user control; existing installs keep whatever value they have.
-- (No-op kept as a comment so the migration file's presence stays consistent.)
